### PR TITLE
moved project directory note

### PR DESCRIPTION
**Pull request by jbenet**
to make it more prominent

### CODE REVIEW

**Comment by jbenet** [comment]
@RichardLitt @mekarpeles how does this look? https://github.com/ipfs/ipfs/blob/move-project-dir-note/README.md -- i'm not sure it's better or worse

**Comment by mekarpeles** [comment]
I think it would be advantageous for the ipfs page (the main page people get sent to) to have high level table of contents and for the other "repos" (pm, notes, specs, apps, etc) to be moved either within ipfs (as is project-directory.md) or within another single repository

= Table of Contents
- Table of Contents (links)
- Implementations
- Client Libraries
- Community Projects (aka Project Directory)
- Specifications (aka specs + security)
- Roadmap (aka PM)

Just my 2 cents

**Comment by jbenet** [comment]
SGTM :+1:

**Comment by RichardLitt** [comment]
I don't that's better, Juan. It's a good idea, but I think that most people landing on this page will actually want to read the IPFS description first. I would move it right above 'Backlog', which should be removed, underneath the description. 

@mekarpeles, I agree about moving notes, specs, apps all into one repository with labels for the issues. I think that makes a lot more sense than all of the current repos we have. I added a TOC into the index here: https://github.com/ipfs/ipfs/pull/124. Is that sort of what you meant?

**Comment by jbenet** [comment]
ok what if we make the project-directory more concise (less spacing), and put it in the README of this repo itself? (someone else -- i think maybe @richardlitt or others -- suggested that before)

- we can also _clearly_ list out all the client api libs.
- we can also make a iswebrtcreadyyet.com table for API completeness.

@mekarpeles thanks for taking the initiative forking stuff over to the org https://github.com/ipfs-client-libraries -- though i dont think this is going to be a good road, because we have _a ton_ of repos which would really explode to 6+ orgs. and the organizational complexity would be way more taxing than helpful (the help as i understand is just that it lists it in one page, which we can probably accomplish by cleaning up this repo readme and making a nice website for it, in https://ipfs.io/docs  ---- we seriously need good docs!

**Comment by mekarpeles** [comment]
@RichardLitt on #124 -- yeah, this is great. My first impression of "project-directory.md" was that it was a listing of community projects (as opposed to "Repository Index" or something). It got me wondering, if that is the index, why is that not part of ipfs/ipfs? Or at least creating a file for each of the sections in project-directory.md and then linking to each one in an ipfs/ipfs table of contents (meaning a TOC which shows up on ipfs/ipfs/README.md)

Trashing https://github.com/ipfs-client-libraries and https://github.com/implementations -- reasoning makes sense to me. Proposing ipfs/ipfs/client-libraries.md and ipfs/ipfs/implementations.md in branch I92/refactor/updating-docs submitted for review: https://github.com/ipfs/ipfs/pull/126

**Comment by jbenet** [comment]
@mekarpeles i also think we should put everything in the ipfs/ipfs/readme.

**Comment by mekarpeles** [comment]
Ok, we can do that

**Comment by RichardLitt** [comment]
@mekarpeles I think you're right that the name _project-directory.md_ can be confusing. I'd be happy to change that to _repository-index.md_. I don't think splitting it up is a good move, though: there are a ton of changes happening to that document all of the time, and I'm already having a hard time keeping it up to date. Having multiple places where it is stored will quickly make it obsolete, inhibit easy searching, and also make it very hard for contributors who don't focus on docs to know where to put new repository information. 

@jbenet hmm not sure about putting project-dir in the readme, it'd be really long, which makes people glaze out. I think an easy compromise is to add in a TOC that points to subsections in the project directory in the main readme.md. How does that sound?

**Comment by RichardLitt** [comment]
I also think making a list of all of the repos on the ipfs.io website would be great. It should be fairly easy to make a script that automatically grabs the project-directory.md file and generates it for the website. I'm happy to build that. What do you think?

**Comment by mekarpeles** [comment]
@RichardLitt -- See: https://github.com/ipfs/ipfs/tree/I92/refactor/updating-docs

The challenge with any sort of sitemap which has links which span multiple repositories (contributing, specs) is that it requires to update contents in multiple places causing data rot and inconsistency. One challenge which is emerging is that people don't know the correct place to look. If we have a repository for specs and community, I am not sure why the ideal solution would be to refer to a site-map.

**Comment by RichardLitt** [comment]
I'm pretty confused: how is factoring project-directory.md out into community, spec, and and ipfs/README.md _not_ going to cause data rot and inconsistency? We don't have substantial lists elsewhere.

**Comment by mekarpeles** [comment]
I'm doing my best to address this confusion. 

Right now we have https://github.com/ipfs/ipfs/blob/master/project-directory.md#specs references to ipdl in our sitemap, but no mention of ipdl on our specs landing page.

We have community tools on https://github.com/ipfs/ipfs/blob/master/project-directory.md#tools, but no way for developers (who are looking for tools in the contributor's guide).

We have a client-library and implementations section which are only discoverable through a single issue thread and through the project-directory (which is not intuitive).

The core of these problems is systemic. It's not a matter of patching "edge cases". It makes sense that we should have a single entry point to the project ipfs/ipf/README.md, and if the user has a question, that we should route them to a single document which will address their question.

I can appreciate you may not agree, but does this resolve the confusion?

**Comment by RichardLitt** [comment]
> I'm doing my best to address this confusion.

Thanks! I'm aware I'm suddenly asking a lot of questions, I just didn't know the reasoning behind recent work, and I've put some amount of effort into project-dir. 

From my perspective, pd.md was the only place to find out what is actually going on in https://github.com/ipfs, in regards to the question I would have (and did have) as a newcomer: why are there so many repositories, where do I get X answered. The document itself has the exact same functionality as searching https://github.com/ipfs, but with semantically appropriate sections, from which they could then find the repository they needed. 

Your solution works better as far as having a single point of truth. 

I'm not sure that it is better in two cases, though. First, when a contributor makes a new IPFS repository, where will that be linked? On IPFS/readme? In whatever category it belongs? I may ask this question only because the idea of having a master repository list makes me feel a bit safer (for no obvious reason that I can tell, except that it seems more organized than only having github.com/ipfs). 

Second, what will be done about all of the random tools that we have on IPFS? CF. https://github.com/ipfs/ipfs/blob/master/project-directory.md#random-modules

**Comment by RichardLitt** [comment]
Thought of two more things: 
- Gutting _project-dir_ also means we'd have to think of a different way of stubbing out a repository index for the website
- I'd like to know: was there a specific issue that resulted in #192? You reference a couple of issues in the commit logs, but one of them is poorly linked I think (https://github.com/ipfs/ipfs/issues/92).

**Comment by mekarpeles** [comment]
https://github.com/ipfs -- this is a listing of all of our repositories which will always be fresh. If the descriptions of the repositories are unclear, I think it makes sense we should work them -- that does make sense to me.

I think it would be worth while to do some user studies and hear new users' frustrations upon their initial experience. I don't recall once when I was first browsing the ipfs/ipfs landing page asking for an "explanation" of all the repositories. I was directed to the ipfs/ipfs/README.md and I had very specific questions I was trying to answer. I was typing Ctrl+f trying to find the text "application" in the README. I then went on irc and asked @jbenet where I could find a list of applications developed by the community. He gave me a "hint" of looking in project-directory.md. I then navigated to a second document, project-directory.md, where I found a site-map and a section with a few applications... And within that very document, I learned there was a https://github.com/ipfs/apps repository... which was empty! All I could think about is... Why couldn't my question be answered directly from the landing page. Or at very least, why couldn't the landing page have a link that says "Community Projects" which takes me directly to https://github.com/ipfs/apps (since the repository is likely there for a reason)?

My point being, I wasn't looking for a site-index. I honestly don't think any user is. The most useful parts about project-directory.md aren't even it's "sitemap" characteristics, but its **answers** to what apps, client-libraries, implementations, and tools are available... But we have repositories dedicated to each of those things.

Trust me, I wish we didn't have so many repositories that a site-index could even make sense as a concept -- but this is a different issue which seems to have been discussed. 

> Gutting _project-dir_ also means we'd have to think of a different way of stubbing out a repository index for the website

A repository listing on ipfs.io? Is this a problem one of our users reported? Were they trying to get a listing of repositories -- and from ipfs.io? I understand, we do have a lot of repositories. The people who aren't familiar with our repositories are likely new users. And a sitemap isn't a direct, easy, or intuitive way for new users to get their questions answered. They want one guarantee:

That all their questions will be directly answered in one location (even if part of the answer requires them to follow a link).

But the following doesn't answer their question it just tells them there's another document which might answer their question (no links, and expectation of what they might find at the end of the tunnel):

`Lost? Searching for something? Need to submit an issue? Want to contribute? Take a peek at project-directory.md which maps out all the repositories for the ipfs project on Github.`

Think about the user's confusion. Is a project-directory the right place to submit an issue? Is it where I should go to learn how to contribute? The frustrating fact is, in this sentence, we **anticipate exactly** what the user cares about... And then we don't answer them. We send them to a different document which is 1/3 awesome-list, 1/3 sitemap, and 1/3 original content (client libraries and implementations and tools) which can't be found anywhere else (even though they are intended to live elsewhere, by virtue of there existing repositories for them). 

For us to do the best job, we need to predict their questions and give them the most direct route to finding an answer, preferably directly through a table of contents. That's my opinion.

I really believe the key, is centralizing all entry at ipfs/ipfs/README.md.

> Second, what will be done about all of the random tools that we have on IPFS? CF.

Who uses or is searching for the random tools? I imagined (maybe incorrectly) contributors + developers are the ones who need these resources. Currently, there's no clear way to learn about these goals from any of our contributor / developer documentation. And how would they even know to check project-directory.md to learn about them? The PR https://github.com/ipfs/community/pull/78 moves these tools into the `ipfs/community/contributing.md` as I figured anyone who has questions about how they can or should contribute will check there for answers. And they will get there from the landing page. Now, there might be a better location than `ipfs/community/contributing.md`, I concede that. I figured someone in the ipfs/community repository would be the most appropriate place for it / where people would expect to search for it).

**Comment by RichardLitt** [comment]
Ok. I agree with most of your points; thank you _so much_ for writing them out. 

>  I don't recall once when I was first browsing the ipfs/ipfs landing page asking for an "explanation" of all the repositories.

I had this problem. I was/am a newcomer, and I just didn't understand what I was looking at. Going through and sorting out what everything was seriously helped me. 

>  I learned there was a https://github.com/ipfs/apps repository... which was empty! 

We _seriously_ need to write up a thing about how we use discussion repos. They historically haven't had much README, because we take it for granted that newcomers know that some repositories only exist in the issues and have no code. (Unless you mean that at the time there were no issues there, as it is relatively new). I have this as a thing to work on.

> Or at very least, why couldn't the landing page have a link that says "Community Projects" which takes me directly to https://github.com/ipfs/apps (since the repository is likely there for a reason)?

I don't think that's the only reason for that repo, but I may be wrong. But yeah, adding a community projects to the main README sounds good. 

> My point being, I wasn't looking for a site-index. I honestly don't think any user is. The most useful parts about project-directory.md aren't even it's "sitemap" characteristics, but its answers to what apps, client-libraries, implementations, and tools are available... But we have repositories dedicated to each of those things.

I was, which is weird, because I am clearly an edge case. Maybe we should add a note saying that we don't have a sitemap. I think what I was looking for was some idea about what is being worked on by the team, and why, and where. The ipfs/pm issues don't really help with that, as they are too person specific. There may not be an answer to this, and it may be me trying to shoehorn myself into a product manager role. I'll try and think of how to do this better, on my own. 

> A repository listing on ipfs.io? Is this a problem one of our users reported? 

I think I may have misunderstood [this comment above](https://github.com/ipfs/ipfs/pull/125#issuecomment-158700708) by @jbenet, which I now think refers to the IFPS client libraries status and not to IPFS repos in general.

> For us to do the best job, we need to predict their questions and give them the most direct route to finding an answer, preferably directly through a table of contents. That's my opinion.

I'm not 100% sure what you mean by TOC. A TOC just links to sections in a document, it doesn't provide information. We need to provide it in a TOC _as well as_ overhauling the Readme, in general. So, for instance, we need to replace the "lost?" question with FAQ questions like, "Where do I submit my issues?" or "How can I contribute?"

> Who uses or is searching for the random tools? I imagined (maybe incorrectly) contributors + developers are the ones who need these resources. Currently, there's no clear way to learn about these goals from any of our contributor / developer documentation. And how would they even know to check project-directory.md to learn about them? The PR ipfs/community#78 moves these tools into the ipfs/community/contributing.md as I figured anyone who has questions about how they can or should contribute will check there for answers. And they will get there from the landing page. Now, there might be a better location than ipfs/community/contributing.md, I concede that. I figured someone in the ipfs/community repository would be the most appropriate place for it / where people would expect to search for it).

Fair point. Moving them to ipfs/community makes some sense. I think it might make sense to make a project-directory.md file in ipfs/community and link to it from community/contributing.md, though, in the interest of shorter readmes, if nothing else. There are some issues right now in the ipfs/community repo, anyway - for instance, the main README.md and Contributing.md have some content that might be best to be merged, and project.md should probably be merged and discarded. 

How do I know, as a contributor, where (my) new repos should be listed? Can we talk about that? Before, I would add them into project-directory.md. Now that there are going to be several, should we even do this anymore? For instance, where should https://github.com/ipfs/post be mentioned? 

## TODO 

Just a few things I pulled out while writing the above.

- [ ] Go through the list of current repositories and make sure that their descriptions are up-to-date.
  - [ ] In particular, changed the *-api repos to "A client library for the IPFS HTTP API, implemented in <language>"
- [ ] Write up a document about what discussion repositories are, and link it in all discussion repositories.
- [ ] Make sure that each repository has a README. Cf https://ipfs.github.io/ci-status/. 
- [ ] Remove the `Lost?` tag. Instead, answer those direct issues in the readme, perhaps in the FAQ.
- [ ] Clean up ipfs/community
  - [ ] Add a TOC to ipfs/community/README.md
  - [ ] Merge and delete ipfs/community/project.md
  - [ ] Update ipfs/community/issues-guide.md (we don't use Waffle anymore, for instance)
  - [ ] Add link to issues guide into ipfs/community/contributing.md

**Comment by mekarpeles** [comment]
I'm understanding your stance better, which is important. Thanks for bearing with my critical response.

> just didn't understand what I was looking at. Going through and sorting out what everything was seriously helped me.

I agree this is a case. I agree the project-directory file had valuable information. Which is why I think this information should be preserved and shown within the main readme.

Ironically, the project-directory had a great TOC. When I first saw that file, my thought was: this file should **be**the readme. I imagine you agree. But if that's the case, let's determine how to preserve and increase its value by showcasing it in readme.

All points in the to-do LGTM

> Write up a document about what discussion repositories are, and link it in all discussion repositories.

And let's address this question in the main README.

> Remove the Lost? tag. Instead, answer those direct issues in the readme, perhaps in the FAQ.

I thought this was done on the latest commit. You're right, there are several unanswered questions we should help the users get to.

 > Clean up ipfs/community
 Add a TOC to ipfs/community/README.md

**Comment by jbenet** [comment]
Closed in favor of https://github.com/ipfs/ipfs/pull/128

**Comment by RichardLitt** [comment]
> And let's address this question in the main README.

Good call. Added to my little list. 

> there are several unanswered questions we should help the users get to.

New todos: 
- [ ] Make sure these questions are in the README or the in the FAQ:
  - [ ] I am lost and looking for something! Where do I go?
  - [ ] Where do I submit an issue?
  - [ ] I want to contribute: where do I go?

Otherwise, thanks so much! This was a really fruitful discussion. Feeling pretty awesome by the changes.

**Comment by RichardLitt** [comment]
(Don't worry, I have these marked down, and will link here accordingly. This thread can die now).

**Pull request closed without merging**
