### PR TITLE
main readme redo

### PR DESCRIPTION
**Pull request by jbenet**
This PR redoes the readme, hopefully satisfying concerns. It covers the major problems discussed with @mekarpeles and @richardlitt.

I think we should move on from this. We can improve from here.

### CODE REVIEW

**Comment by jbenet** [comment]
#### Take a look here: https://github.com/ipfs/ipfs/blob/redo-readme/README.md

**Comment by mekarpeles** [comment]
lgtm

**Comment by RichardLitt** [comment]
lvgtm

**Comment by jbenet** [comment]
@mekarpeles @RichardLitt thank you so, so much for contributing to this effort, bearing with all my silly nitpicks, and improving this dramatically. this will help all our community! :heart:

**Comment by mekarpeles** [comment]
@RichardLitt thanks for talking points through w/me, proving well reasoned feeback and a necessary alternate perspective, getting me up to speed w/ history and conventions, and providing us with a very solid foundation of resources from project-directory.md which powered this update.

Q.E.D. I have a direct personality (which I try to focus at problems rather than people) so thanks @jbenet and @RichardLitt for keeping discussion objective and productive. Looking forward to future discussion + progress.

**Comment by harlantwood** [comment]
Looks great.

**Comment by RichardLitt** [comment]
@jbenet No problem! Thanks for helping out. 

@mekarpeles Thank you! I really appreciate it. :) I try to focus the story and understanding and not the problems, which sometimes means I talk a lot, so thanks for helping me out there. Looking forward to working with you further. Also, thanks for the thanks - it means a lot.

**Pull request merged**
