### PR TITLE
Update C# API lib to a more complete one (check dev branch)

### PR DESCRIPTION
**Pull request by slothbag**
I tried the original lib and it was only 20% complete, then I found this lib which is probably about 90% complete.

### CODE REVIEW

**Comment by RichardLitt** [comment]
The one you link to has no contents, and only one commit. Are you sure you linked it right? Also, no reason for the `.git` ending.

**Comment by slothbag** [comment]
Yup, its the right one, check the develop branch.

I have updated it to remove the .git, plus I added the "check develop branch" text.

**Comment by slothbag** [comment]
Developer has moved all the latest changes from develop to master, no need for the note any more.

**Comment by whyrusleeping** [comment]
This LGTM. The repo you linked to appears to be far more maintained. Thanks!

**Pull request merged**
