### PR TITLE
Added  ` - ` between links and descriptions, final periods

### PR DESCRIPTION
**Pull request by RichardLitt**
This should make the list a bit more readable. Right now, it is fairly scrunched up.

License: MIT
Signed-off-by: Richard Littauer <richard.littauer@gmail.com>

### CODE REVIEW

**Comment by ion1** [comment]
If you want to be extra fancy, you could use the en dash (–) instead of a hyphen. :-)

**Comment by RichardLitt** [comment]
Haha. I just want to make it a bit more readable, I think a normal dash should be fine.

**Comment by Dignifiedquire** [comment]
LGTM

**Comment by RichardLitt** [comment]
Thanks. Waiting for @jbenet's response on this, as it is ipfs/ifps.

**Pull request merged**
