### PR TITLE
Add Changelog episode badge to README

### PR DESCRIPTION
**Pull request by jerodsanto**
Thanks for coming on the show @jbenet! I added this badge to the README to share your episode with the community. 🍻

Links to: https://changelog.com/204

### CODE REVIEW

**Comment by RichardLitt** [comment]
@jerodsanto Hey! So; I've been thinking that this might be better to put on [ipfs/awesome-ipfs](//github.com/ipfs/awesome-ipfs). I am going to add it there and close this; hope that's OK!

**Comment by jerodsanto** [comment]
@RichardLitt this show has been listened to by over 40k developers and we've had countless people tell us it's helped them better understand IPFS and check it out more.

Audio is a great way to add context and humanity around software efforts. I think burying this at the bottom of an awesome-* list isn't doing it (or your goals with IPFS) any service.

_(Also if you check the reactions to the PR, @jbenet seems pretty enthusiastic about it)_

Ultimately, it's your call, of course!

**Comment by RichardLitt** [comment]
I did not realize it had such a huge following, or that this was viewed that much. Whoa. OK. I am just going to merge this now. Thanks!

**Comment by jerodsanto** [comment]
Thanks Richard! ✊

**Pull request merged**
